# render.yaml para el proyecto Genisthis
# Definición de servicios para desplegar n8n en Render

services:
  # 1. Base de Datos PostgreSQL para Genisthis (datos internos de n8n)
  - type: pserv # Servicio Privado (Base de Datos)
    name: genisthis-n8n-postgres # Nombre actualizado para claridad: proyecto-n8n-recurso
    region: us-east-1 # Región N. Virginia (recomendada)
    plan: free # Plan gratuito inicial

  # 2. Servicio Web para n8n (instancia principal de Genisthis)
  - type: web # Servicio Web
    name: genisthis-n8n-web # Nombre actualizado para claridad: proyecto-n8n-recurso
    region: us-east-1 # Misma región que la base de datos
    plan: free # Plan gratuito inicial (considera 'starter' para producción)
    healthCheckPath: /healthz # Ruta para verificación de salud de n8n
    image:
      url: n8nio/n8n:latest # Imagen oficial de n8n (puede fijar una versión: n8nio/n8n:1.2.3)
    envVars:
      # --- Conexión a la Base de Datos ---
      - key: DB_TYPE
        value: postgresdb
      - key: DATABASE_URL
        fromService:
          type: pserv
          # !! Asegúrate que 'name' coincide con tu servicio de BD actualizado !!
          name: genisthis-n8n-postgres
          envVarKey: DATABASE_URL # Render genera esta variable automáticamente

      # --- Configuración General de n8n ---
      - key: GENERIC_TIMEZONE
        # !! Zona horaria ajustada para el público principal (Brasil - São Paulo) !!
        # Esto afecta cómo se interpretan las programaciones (cron) y cómo se muestran las horas en la UI de n8n.
        value: America/Sao_Paulo
      - key: WEBHOOK_URL
        fromService:
          type: web
          # !! Asegúrate que 'name' coincide con este servicio web actualizado !!
          name: genisthis-n8n-web
          envVarKey: RENDER_EXTERNAL_URL # Render genera esta variable automáticamente

      # --- Variables Secretas (usando un Grupo de Variables de Entorno) ---
      # !! MUY IMPORTANTE: Debes crear un 'Environment Group' llamado 'genisthis-n8n-secrets'
      # !! en el dashboard de Render ANTES de desplegar. Este grupo DEBE contener al menos
      # !! la variable N8N_ENCRYPTION_KEY con una clave segura que generes.
      # !! Si este grupo no existe o está vacío, el despliegue puede fallar con errores de validación.
      - group: genisthis-n8n-secrets # Nombre del grupo que crearás en Render (actualizado)

      # Nota: La N8N_ENCRYPTION_KEY es *obligatoria*. Ponla en el grupo 'genisthis-n8n-secrets'.
